---
- name: Install Packages
  apt: name={{ item }} state=latest update_cache=true
  with_items:
   - python2.7 
   - python2.7-dev
   - python-dev 
   - python-libpcap
   - python-elixir
   - python-ipy
   - python-glade2
   - python-dnspython
   - python-geoip
   - python-whois
   - python-requests
   - python-ssdeep
   - python-ldap
   - python-setuptools
   - python-pip
   - python-protobuf
   - python-libpcap 
   - python-elixir 
#   - python-support 
   - python-ipy 
   - python-glade2 
   - python-dnspython 
   - python-geoip 
   - python-whois 
   - python-requests 
   - python-ssdeep 
   - python-ldap 
   - python-setuptools 
   - libxml2-dev 
   - libxslt1-dev 
   - zlib1g-dev 
   - protobuf-compiler
   - build-essential 
   - libssl-dev 
   - libffi-dev
   - autoconf 
   - libtool 
   - pkg-config 
   - python-opengl 
   - python-imaging 
   - python-pyrex 
   - python-pyside.qtopengl 
   - idle-python2.7 
   - qt4-dev-tools 
   - qt4-designer 
   - libqtgui4 
   - libqtcore4 
   - libqt4-xml 
   - libqt4-test 
   - libqt4-script 
   - libqt4-network 
   - libqt4-dbus 
   - python-qt4 
   - python-qt4-gl 
   - libgle3 
   - libssl-dev
   - python3-dev
  register: results
  until: results is success
  retries: 10
  delay: 3


- name: Python startup config
  template:
    src: pythonstartup.j2
    dest: /root/.pythonstartup

- name: Install pip packages
  pip:
    name: "{{ item }}"
#    version: 0.11
  with_items:
    - pip
    - xlrd
    - google-api-python-client
    - shodan
    - pytz 
    - python-qt 
    - flickrapi 
    - python-instagram 
    - yapsy 
    - tweepy 
    - google-api-python-client 
    - python-dateutil 
    - configobj 
    - dominate 
    - github3.py
    - editorconfig
    - selenium
  register: results
  until: results is success
  retries: 10
  delay: 3

- name: Create Python Environment directory
  file:
    path: /opt/python/venv/
    state: directory
    recurse: yes
