---

- name: Shorten Grub Timeout
  become: yes
  become_user: root
  replace:
    path: /etc/default/grub
    regexp: GRUB_TIMEOUT=.*
    replace: GRUB_TIMEOUT=1
    backup: yes

- name: Change TTY resolution
  become: yes
  become_user: root
  replace:
    path: /etc/default/grub
    regexp: GRUB_CMDLINE_LINUX_DEFAULT=.*
    replace: GRUB_CMDLINE_LINUX_DEFAULT="vga=0x0318"
    backup: yes

- name: Update Grub
  become: yes
  become_user: root
  shell: update-grub
